### ISSUE TITLE
Update User creating duplicate row 

### ISSUE THREAD

**Issue by zaheenzkhan** [jithinjohn7/Kitchen_Assistant#3]
The update user profile query seems to create a duplicate user in the database. Find query is wrongly written I guess. @ssudame0412

**Comment by zaheenzkhan** [comment]
update(req, res) {
User.findById(req.params.id).then(function(user) {        
             return user
	      .update({
	    	  firstName: req.body.firstName,
	          lastName: req.body.lastName,
	          email: 	req.body.email,
	          password: 	req.body.password,
	      })
	      .then(user => res.status(201).send(user))
	      .catch(error => res.status(400).send(error));
		})
	     }

**Comment by jithinjohn7** [comment]
this is now fixed with retrieving the object to be updated using a find query and then updating using udpate query.
