### ISSUE TITLE
Case insensitivity required client Object mapper

### ISSUE THREAD

**Issue by jithinjohn7** [jithinjohn7/Kitchen_Assistant#7]
Jackson version need to be updated to 2.5.0 and above to use case-insensitive json to object mapping in android client. 

`ObjectMapper mapper = new ObjectMapper();
                try {
                    InventoryModel response = mapper.readValue(jsonObject.toString(), InventoryModel.class);`

**Comment by zaheenzkhan** [comment]
Mapper version updated to 2.9.0 to support Case Insensitivity. 
Nested Json Issue also fixed simultaneously.
Fixed in commit 5cc8521d67c79120afb7468c795aa59cd3269d56
